version: "3.8"
services:

  db:
    image: postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: example

  scraper:
    build:
      context: ./scraper
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: example
      USER_IDENTIFIER: "${USER_IDENTIFIER}"
      SECRET_NUMBER: "${SECRET_NUMBER}"
      YNAB_TOKEN: "${YNAB_TOKEN}"
      PGHOST: 'db'
      PGUSER: scraper
      PGPASSWORD: example
      PGPORT: 5432

networks:
  backend:

volumes:
  db-data: