version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    working_directory: ~/millennium-scraper/scraper
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout:
          path: ~/millennium-scraper
      - run: npm install
      - run: npm start

