# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: scraper

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm start
      env:
        USER_IDENTIFIER: ${{ secrets.USER_IDENTIFIER }}
        SECRET_NUMBER: ${{ secrets.SECRET_NUMBER }}
        YNAB_TOKEN: ${{ secrets.YNAB_TOKEN }}
        YNAB_ACCOUNT_ID: ${{ secrets.YNAB_ACCOUNT_ID }}
